/****** Object: Table [dbo].[bpjs_refpoli]   Script Date: 21/09/2023 14.24.03 ******/
USE [banjar];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[bpjs_refpoli] (
[KDPOLI] varchar(3) NOT NULL,
[NMPOLI] varchar(50) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[bpjs_refpoli] SET (LOCK_ESCALATION = TABLE);
GO


insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('AKP','Akupuntur')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('ALG','Alergi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('ANA','ANAK')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('ANU','Anuscopy')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('APT','APOTIK')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('ASM','ASM')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('BDS','BDS')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('BED','BEDAH')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('BSY','BEDAH SARAF')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('CAN','CAN')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('CAP','Unit Pelayanan CAPD')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('CTS','CT Scan')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('DBM','Diabetes Melitus')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('DRH','Darah')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('ECO','Echo')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('EKG','Rekam Jantung')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('ELK','ELK')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('END','Endokrin')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('ESW','ESWL')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('FIS','Fisioterapi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('GAS','Gastro')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('GER','Geriatri')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('GIG','GIGI')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('GIN','Ginjal')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('GIZ','GIZI KLINIK')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('GP1','Gigi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('GTS','GILA')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('HAM','HAM')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('HCU','High Care Unit')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('HDL','HEMODIALISA')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('HEM','Hematologi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('HEP','Hepatologi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('HIV','B20')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('ICU','Intensive Care Unit')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('IGD','INSTALASI GAWAT DARURAT')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('IKA','Ilmu Kesehatan Anak')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('INF','INSTALASI FARMASI')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('INT','PENYAKIT DALAM')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('IPD','Ilmu Penyakit Dalam')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('IRM','REHABILITASI MEDIK')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('IVP','Intravena Pydografi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('JAN','JANTUNG DAN PEMBULUH DARAH')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('JIW','JIWA')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('JWA','Jiwa Anak')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('JWD','Jiwa Dewasa')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('KLT','KULIT KELAMIN')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('KOL','KOL')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('LAB','Laboratorium')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('LAI','Lain-Lain')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('MAT','MATA')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('MRI','MRI')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('NUK','Radioterapi/Nuklir')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('OBG','OBGYN')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('OKM','OKM')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('OPT','OPTIK')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('ORT','ORTHOPEDI')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('OTL','OTL')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('PAR','PARU')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('PAT','PAT')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('PKM','PUSKESMAS')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('PMI','PMI')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('PNM','GIGI PENYAKIT MULUT')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('PPK','PPK')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('PSI','PSI')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('PSK','PSK')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('PUL','Pulmonologi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('R12','Boneseah')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('RAA','Radiologi Anak')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('RAD','Radiologi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('RAT','Radioterapi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('REM','REM')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('RHM','Rheumatologi')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('RO2','RO2')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('SAR','SARAF')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('SPC','SPC')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('TAK','TAK')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('THT','THT-KL')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('TON','TON')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('TRD','Treadmil Test')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('TUM','TUM')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('UGD','Unit Gawat Darurat')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('URE','URE')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('URF','URF')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('URO','URO')
insert into [dbo].[bpjs_refpoli]([KDPOLI],[NMPOLI]) values ('USG','USG')

GO
